### PR TITLE
Use postcard instead of bincode for serialization

### LINKED ISSUE #776: Investigate alternatives to bincode serialization
Maybe instead of `serde` and `bincode`, we could use something like [`rkyv`](https://docs.rs/rkyv/latest/rkyv/)? In any case, `bincode` format isn't stable across Rust versions and should not be used for persistent storage.

### LINKED ISSUE #905: Replace p2p bincode codec with a more stable serialization format
P2P currently uses bincode for messaging due to simplicity, however it is not a safe format to use for networked services as the format could change due to simply upgrading rust.

Protobuf is likely the most standard/straightforward option, but we can consider alternatives such as cbor/msgpack as well.

### PR DESCRIPTION
**Pull request by Dentosal**
[Postcard](https://github.com/jamesmunns/postcard) is a drop-in replacement for bincode. It has [almost identical performance characteristics, but it's bit a more comact](https://github.com/djkoloski/rust_serialization_benchmark) and [stable across Rust versions](https://github.com/jamesmunns/postcard#format-stability). It recently reached 1.0 and is considered rather stable.

This PR simply replaces all invocations to bincode with their postcard equivalents. Closes #905 and closes #776

### CODE REVIEW

**Comment by ControlCplusControlV** [comment]
Is there a reason you chose Postcard? I know we discussed `rkyv` a while back for performance reasons, and because its been battle tested with Solana

**Comment by Dentosal** [comment]
The reason for use `postcard` is that it works as a drop-in replacement and fullfills our needs. While `rkyv` is a bit faster than `postcard`, it sometimes produces significantly larger output. I'm going to investigate `rkyv` later this week, but this PR provides a simple way to fix all known issues about our current code, i.e. data format non-stability across Rust versions.

**Review by leviathanbeak — CHANGES_REQUESTED** [review]
In p2p, `postcard` codec is directly implemented within `bincode` codec, it should be a separate implementation (I don't mind renaming existing file) but all references to `bincode` should be removed

**Comment by freesig** [comment]
> In p2p, `postcard` codec is directly implemented within `bincode` codec, it should be a separate implementation (I don't mind renaming existing file) but all references to `bincode` should be removed/replaced

Yeh I wonder how this will affect things like https://github.com/FuelLabs/fuel-core/blob/4c945a91f2472d0cd44b82f5afb0a738e3bb9522/crates/services/p2p/src/codecs/bincode.rs#L289

**Comment by freesig** [comment]
For example https://github.com/FuelLabs/fuel-core/blob/4c945a91f2472d0cd44b82f5afb0a738e3bb9522/crates/services/p2p/src/request_response/messages.rs#L28
is probably no longer correct?

**Comment by leviathanbeak** [comment]
> For example
> 
> https://github.com/FuelLabs/fuel-core/blob/4c945a91f2472d0cd44b82f5afb0a738e3bb9522/crates/services/p2p/src/request_response/messages.rs#L28
> 
> 
> is probably no longer correct?

@freesig why not? Does `postcard` mess up the size?
As far as I see it, that piece of code should not change irrespective of the serializer, it's just the size of the biggest enum variant.

**Comment by Dentosal** [comment]
> As far as I see it, that piece of code should not change irrespective of the serializer, it's just the size of the biggest enum variant.

Postcard is able to reduce the size, likely by encoding the enum tag as a single-byte varint instead of u32. I've updated the check to use `<` instead of equality.

**Comment by leviathanbeak** [comment]
> Postcard is able to reduce the size, likely by encoding the enum tag as a single-byte varint instead of u32. I've updated the check to use `<` instead of equality.

that's actually good news, maybe still having `<=` cuz even if it's equal it should be fine and the test should convey that imo,
as for the rest of the code I will review it tomorrow morning

**Review by Voxelot — DISMISSED** [review]

**Review by Voxelot — APPROVED** [review]

**Review by leviathanbeak — APPROVED** [review]
🥇

**Pull request merged**
