### PR TITLE
Use sticky session for the client

### PR DESCRIPTION
**Pull request by xgreenx**
This branch is a hotfix for beta 3 to support sticky session on the client. The change enables cookies for the `reqwest` and reuse them for the subscription

### CODE REVIEW

**Comment by Voxelot** [comment]
needs a version bump

**Comment by Voxelot** [comment]
This seems to work better in the e2e environment, nice work

**Review by Voxelot — APPROVED** [review]

**Comment by Voxelot** [comment]
:shipit:

**Comment by xgreenx** [comment]
The release is published, so we can close it now

**Pull request closed without merging**
