### PR TITLE
fix: fuel-core-keygen support --version arg

### LINKED ISSUE #1495: `fuel-core-keygen` should support `--version` arg
Fuelup expects all components to implement the `--version` argument.

Related: https://github.com/FuelLabs/fuelup/issues/508

### PR DESCRIPTION
**Pull request by lilasxie**
Close #1495 

image

### CODE REVIEW

**Comment by xgreenx** [comment]
Thank you, but we don't want to accept super small PRs from accounts without real Github activity

**Comment by lilasxie** [comment]
> Thank you, but we don't want to accept super small PRs from accounts without real Github activity

This is ridiculous. As this is a PR for a good_first_issue, and just a bug fix, no more code is needed.

**Comment by lilasxie** [comment]
> Thank you, but we don't want to accept super small PRs from accounts without real Github activity

And what do you mean my saying 'no real Github activity'? I'm doing some contributions to open-source project, and I need to work also, no one should be stay github all the day.

**Comment by xgreenx** [comment]
The problem is that you created a bunch of small PRs in several blockchain projects.

image

For example, the change below is unnecessary at all:
image

It looks like you are trying to get some contributions for the twink account to blockchain projects to receive some airdrops in the future.

We are happy to accept small contributions from the main GitHub account. If it is a new account(twink), we are okay with accepting really valuable changes.

**Comment by lilasxie** [comment]
> The problem is that you created a bunch of small PRs in several blockchain projects.
> 
> image
> For example, the change below is unnecessary at all: image
> 
> It looks like you are trying to get some contributions for the twink account to blockchain projects to receive some airdrops in the future.
> 
> We are happy to accept small contributions from the main GitHub account. If it is a new account(twink), we are okay with accepting really valuable changes.

Okay, I got you. It is up to u to judge me like this. But here are some clarification:
1. As you mentioned about the PR for osmosis, if u are new to golang, plz re-check for the PR as I described. This PR is  created when I reviewed the code, and was confused about the variable declared, although this makes no real effect for running, but for reading.
2. No matter what am I a new account, or twink, doesn't this "fix" PR make a valuable changes? If u guys can do this easily, plz don't leave this a good-first-issue, just fix it on your own asap okay?
3. I don't care about the airdrop, I care about what I can do for the world😀

**Pull request closed without merging**
