### PR TITLE
Update to Rust 1.67 and FIx Clippy Lints

### PR DESCRIPTION
**Pull request by ControlCplusControlV**

### CODE REVIEW

**Comment by ControlCplusControlV** [comment]
Mainly thinking of updating so soon because of the [fuel-vm pr](https://github.com/FuelLabs/fuel-vm/pull/332) to use new stabilized std lib function, so would be good to ensure everything is on the same version

**Review by leviathanbeak — APPROVED** [review]
clippy ftw

**Comment by ControlCplusControlV** [comment]
Do we need another review before merge? I know updating rust versions can sometimes break things so a bit hesitant to merge but if its fine I can

**Review by freesig — APPROVED** [review]
I think it's fine to merge

**Review by xgreenx — APPROVED** [review]

**Comment by Voxelot** [comment]
We should also update the rust version in our docker image build as well

**Pull request merged**
