### PR TITLE
Improvements for keygen cli and crates

### PR DESCRIPTION
**Pull request by cr-fuel**
Import improvements from https://github.com/FuelLabs/sway/pull/5153.

Once this PR is merged and a new release is created sway will reference this crate instead of having its own copy (https://github.com/FuelLabs/sway/issues/5170)

### CODE REVIEW

**Comment by bvrooman** [comment]
Might just be me, but the "press any key" part doesn't seem to work:

Screenshot 2023-10-31 at 12 20 51 PM

**Comment by cr-fuel** [comment]
@bvrooman You are right, it has to be `enter`. I'll improve that bit.

**Comment by cr-fuel** [comment]
@bvrooman it should be fixed now.

**Review by Voxelot — APPROVED** [review]
nice refactor - definitely cleans up the keygen lib a lot by moving all the cli deps to the binary crate

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
