### PR TITLE
doc: refine the transaction example in the README

### PR DESCRIPTION
**Pull request by mmyyrroonn**
I tried the command in the readme and met the following errors during my work
```sh
thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
invalid transaction json: Error("missing field `script`", line: 1, column: 133)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I replaced it with the `tx` from the test file below by using the function `to_json()`
https://github.com/FuelLabs/fuel-core/blob/a9e5e89f5fb38e3b3d6e6bdfe1ad339a01f2f3b9/tests/tests/tx.rs#L155-L172

### CODE REVIEW

**Comment by MitchTurner** [comment]
Thanks for the contribution!

Interesting. I actually get a different error:
```
thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
invalid transaction json: Error("unrecognized named flag `GasPrice`", line: 1, column: 67)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However, your change still makes it valid :)

**Comment by mmyyrroonn** [comment]
> Thanks for the contribution!
> 
> Interesting. I actually get a different error:
> 
> ```
> thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
> invalid transaction json: Error("unrecognized named flag `GasPrice`", line: 1, column: 67)
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> However, your change still makes it valid :)

Yes. You're correct. That's the first error message I met. I changed it to the `MaxFee` and will meet more errors. I just pick one error message to demonstrate the problem. 😄 I assume the example is out-of-date due to the quick development.

**Comment by netrome** [comment]
> > Thanks for the contribution!
> > Interesting. I actually get a different error:
> > ```
> > thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
> > invalid transaction json: Error("unrecognized named flag `GasPrice`", line: 1, column: 67)
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, your change still makes it valid :)
> 
> Yes. You're correct. That's the first error message I met. I changed it to the `MaxFee` and will meet more errors. I just pick one error message to demonstrate the problem. 😄 I assume the example is out-of-date due to the quick development.

Nice! I've also tried this now. The updated transaction seems to be valid, but trying to add it to the chain results in the error `Transaction is not inserted. UTXO does not exist` when running fuel core with `./target/debug/fuel-core run --db-type in-memory`. The UTXO validation can be turned off by adding the `--debug` flag, hence running `./target/debug/fuel-core run --db-type in-memory --debug`.

While you're at it, can you add a line to the `cURL example explaining to run the node with `./target/debug/fuel-core run --db-type in-memory --debug` for the example to be accepted by the node?

**Comment by mmyyrroonn** [comment]
> > > Thanks for the contribution!
> > > Interesting. I actually get a different error:
> > > ```
> > > thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
> > > invalid transaction json: Error("unrecognized named flag `GasPrice`", line: 1, column: 67)
> > > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However, your change still makes it valid :)
> > 
> > 
> > Yes. You're correct. That's the first error message I met. I changed it to the `MaxFee` and will meet more errors. I just pick one error message to demonstrate the problem. 😄 I assume the example is out-of-date due to the quick development.
> 
> Nice! I've also tried this now. The updated transaction seems to be valid, but trying to add it to the chain results in the error `Transaction is not inserted. UTXO does not exist` when running fuel core with `./target/debug/fuel-core run --db-type in-memory`. The UTXO validation can be turned off by adding the `--debug` flag, hence running `./target/debug/fuel-core run --db-type in-memory --debug`.
> 
> @mmyyrroonn while you're at it, can you add a line to the `cURL` example explaining to run the node with `./target/debug/fuel-core run --db-type in-memory --debug` for the example to be accepted by the node?

It's a good suggestion. I added one sentence to demonstrate the `--debug` flag. It's working successfully right now. 😄

**Comment by Dentosal** [comment]
Related: https://github.com/FuelLabs/fuel-core/issues/1669

**Comment by mmyyrroonn** [comment]
Should I add a change log for this PR? 😄

**Comment by netrome** [comment]
> Should I add a change log for this PR? 😄

I don't think this needs a change log (@MitchTurner please correct me if I'm mistaken), so you can add the `no-changelog` label.

**Comment by mmyyrroonn** [comment]
> > Should I add a change log for this PR? 😄
> 
> I don't think this needs a change log (@MitchTurner please correct me if I'm mistaken), so you can add the `no-changelog` label.

That's cool. However, it seems that I cannot modify the label of this PR.

**Review by netrome — APPROVED** [review]

**Pull request merged**
