### PR TITLE
Removed state transition bytecode from the local testnet

### PR DESCRIPTION
**Pull request by xgreenx**
Closes https://github.com/FuelLabs/fuel-core/issues/2200

## Checklist
- [x] New behavior is reflected in tests

### CODE REVIEW

**Review by MitchTurner — APPROVED** [review]

**Review by rymnc — DISMISSED** [review]

**Comment by rymnc** [comment]
i wonder if we should add this to the gitignore too

**Comment by acerone85** [comment]
source ci_checks.sh adds back the wasm_bytecode file. Maybe best to add it to .gitignore?

**Comment by xgreenx** [comment]
> source ci_checks.sh adds back the wasm_bytecode file. Maybe best to add it to .gitignore?

Yeah, could you do that an commit to this branch please?=)

**Comment by acerone85** [comment]
> > source ci_checks.sh adds back the wasm_bytecode file. Maybe best to add it to .gitignore?
> 
> Yeah, could you do that an commit to this branch please?=)

done,  see 976ce3c04b. Just to understand the workflow, is it okay in general to add commits with minor changes to other people branches?  (We tended to avoid that in my previous company)

**Review by acerone85 — APPROVED** [review]

**Comment by xgreenx** [comment]
> done, see https://github.com/FuelLabs/fuel-core/commit/976ce3c04b68e51a7fa97a7c507afbd2a2ccc8a8. Just to understand the workflow, is it okay in general to add commits with minor changes to other people branches? (We tended to avoid that in my previous company)

The good tone is to create a PR into the initial branch and wait for the owner to accept it, or start some discussion.

I don't mind submitting small things in my PRs=) But it is the preference of everyone=)

I have a bad habit of submitting to people's PR without approval from them. I need to work on it=)

**Review by MitchTurner — APPROVED** [review]

**Pull request merged**
