### PR TITLE
style: %s/produce_block/produce_blocks/g

### PR DESCRIPTION
**Pull request by vnepveu**
Since the argument can be multiple blocks, it makes sense for it to be plural.

### CODE REVIEW

**Comment by ControlCplusControlV** [comment]
@vnepveu these changes just rename the client function. Do you want me to push changes actually renaming the gql endpoint for consistency?

**Comment by vnepveu** [comment]
> @vnepveu these changes just rename the client function. Do you want me to push changes actually renaming the gql endpoint for consistency?

Yes I completely forgot it would make much more sense!

**Review by ControlCplusControlV — APPROVED** [review]
LGTM, just requesting a quick glance from Brandon to make sure it's good to go

**Review by ControlCplusControlV — APPROVED** [review]
Changes LGTM, you should be good to merge once CI lands

**Pull request merged**
