### PR TITLE
chore: Reviewed Imports

### PR DESCRIPTION
**Pull request by Ch1n3du**
I've been able to format most of the imports but I think I caused a lifetime error in `fuel-core` in `fuel-core/src/schema/dap.rs` line 445 and 469 and in `fuel-core/src/schema/message.rs` line 17 not really sure how to fix it and would love any help. #537

### CODE REVIEW

**Comment by ControlCplusControlV** [comment]
@Ch1n3du looks like there are still some importing and other compilation errors, let me know if you need help fixing them

**Comment by Ch1n3du** [comment]
> @Ch1n3du looks like there are still some importing and other compilation errors, let me know if you need help fixing them

Sorry for not replying sooner, I fell ill but I highlighted the issues I was having at the top of the pr, not really sure how to solve them as they have to do with lifetimes and a proc macro I can't figure out

**Comment by xgreenx** [comment]
Hmm, I think we already did it with new rustfmt rules https://github.com/FuelLabs/fuel-core/pull/575 and https://github.com/FuelLabs/fuel-core/pull/605

**Comment by Voxelot** [comment]
Thanks for the PR, but as @xgreenx has mentioned we've largely automated this via nightly rustfmt features.

**Pull request closed without merging**
