### PR TITLE
Refactor: Simplify transaction handling and gas calculations

### PR DESCRIPTION
**Pull request by cypherpepe**
## Linked Issues/PRs

N/A

## Description

This refactor simplifies transaction handling and gas calculations by:
- Removing redundant transaction type checks in `MaybeCheckedTransaction::id()` by centralizing the logic.
- Refactoring the `max_gas()` method to handle common transaction types (Script, Create, Upgrade, Upload, and Blob) in a single match arm, reducing code duplication.
- Preserving special handling for Mint transactions, which do not have `max_gas`.
- Improving overall code clarity and maintainability.

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [x] I have reviewed the code myself
- [x] I have created follow-up issues caused by this PR and linked them here

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

### CODE REVIEW

**Comment by xgreenx** [comment]
Could you try to run `./ci_checks.sh` locally and fix all issue, please?=)

**Review by MitchTurner — APPROVED** [review]
LGTM

**Review by xgreenx — COMMENTED** [review]
Please revert formatting changes, it is too many modifications

**Comment by MitchTurner** [comment]
There seem to be a lot of formatting and other changes that weren't there when I first reviewed.

**Comment by cypherpepe** [comment]
> Could you try to run `./ci_checks.sh` locally and fix all issue, please?=)

Hi! After running the check and fixing the issues in my commits, all problems have been resolved. Please take a look at the changes and let me know if anything else needs attention. Thanks for your patience!

**Comment by cypherpepe** [comment]
> There seem to be a lot of formatting and other changes that weren't there when I first reviewed.

The script `./ci_checks.sh` detected type incompatibilities, and fixing them resulted in an increase in the amount of code. These modifications were necessary for the code to function correctly.

**Comment by xgreenx** [comment]
I am closing this PR for now since the comment to revert formatting changes has not been resolved for a long period of time.

If you still want to contribute, please address comments and create a new PR with link to this one=)

**Pull request closed without merging**
